comment:
  on-update: recreate
  header: |
    Test failed :rage3:.

  footer: |
    ---
    Automated comment created by :robot:.

  snippets:
    - id: any-markdown-file-changed
      files:
        - '*'
      body: |
        - today: {{ today }}
        - pr_author: {{ pr_author }}
        - github_ref: {{ github_ref }}
