name: Deploy develop

on:
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: itering/actions
          path: .github/actions
          persist-credentials: false
          ssh-key: "${{ secrets.ITERING_ACTIONS_DEPLOY_KEY }}"

#      - uses: ./.github/actions/smart-vercel
#        name: Deploy to Vercel
#        id: smart-vercel
#        with:
#          vercel_token: ${{ secrets.VERCEL_TOKEN }}
#          vercel_group: itering
#          preview_output: true

      - name: Completed deploy
        run: |
          mkdir -p deploy
          echo '${{ steps.smart-vercel.outputs.PREVIEW_OUTPUT }}' > deploy/vercel-output.log
          echo '${{ steps.smart-vercel.outputs.PREVIEW_LINK }}' > deploy/vercel-preview.log

      - uses: actions/upload-artifact@v1
        with:
          name: deploy
          path: deploy
