name: Deploy production

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: itering/actions
          path: .github/actions
          persist-credentials: false
          ssh-key: '${{ secrets.ITERING_ACTIONS_DEPLOY_KEY }}'

      - uses: ./.github/actions/smart-vercel
        name: Deploy to Vercel
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          script_run: false
          dist_path: .
          preview_output: true
          prod_mode: true
