name: Notify dev

#on:
#  pull_request:

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed
#    types:
#      - completed


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - uses: actions/download-artifact@v3
        with:
          name: deploy
          path: deploy

      - uses: pCYSl5EDgo/cat@master
        id: vercel
        with:
          path: deploy/vercel.log

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: wormhole-ui
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/14985020?s=48&v=4
          SLACK_MESSAGE: '${{ steps.vercel.outputs.text }}'
          SLACK_TITLE: Preview
          SLACK_USERNAME: Vercel
          SLACK_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

