name: Test

on:
  push:
    branches: [staging, master]
  pull_request:
    branches: [staging, master]

jobs:
  test-cypress:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Custom tests 🧪
        uses: cypress-io/github-action@v2
        with:
          build: yarn install
          start: yarn start
          command: yarn test:e2e:ci
          record: true
          parallel: true
          group: 'Actions example'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Comment
        uses: exercism/pr-commenter-action@v1.3.0
        if: failure()
        with:
          template-variables: |
            {
              "today": "${{ steps.vars.outputs.today }}",
              "pr_author": "${{ github.event.pull_request.user.login }}",
              "github_ref": "${GITHUB_REF}"
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/commenter/pr-cypress.yml
