name: Test

on:
  push:
    branches: [staging, master]
  pull_request:
    branches: [staging, master]

jobs:
  test-cypress:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start server
        uses: cypress-io/github-action@v2
        with:
          build: yarn install
          start: yarn start

      - name: Custom tests 🧪
        uses: cypress-io/github-action@v1
        with:
          command: yarn test:e2e:ci
#  test-unit:
#    name: Run unit test
#    runs-on: ubuntu-latest
#    needs: [install-dependencies]
#    container: cypress/browsers:node14.16.0-chrome90-ff88
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '14.16'
#      - name: Cache node_modules
#        uses: actions/cache@v2
#        with:
#          path: node_modules
#          key: ${{ runner.os }}-node_modules
#      - name: Run unit test
#        env:
#          CYPRESS_CACHE_FOLDER: ./node_modules/cypress/
#        run: yarn test:unit:ci
#
#  test-cypress:
#    name: Run cypress test
#    runs-on: ubuntu-latest
#    needs: [install-dependencies]
#    container: cypress/browsers:node14.16.0-chrome90-ff88
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '14.16'
#      - name: Cache node_modules
#        uses: actions/cache@v2
#        with:
#          path: node_modules
#          key: ${{ runner.os }}-node_modules
#      - name: Run unit test
#        env:
#          CYPRESS_CACHE_FOLDER: ./node_modules/cypress/
#        run: yarn test:e2e:ci
