name: E2E Test

on:
  pull_request:
    branches: [staging, master]

jobs:
  test-cypress:
    name: E2E
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.17.0-chrome88-ff89
      options: --privileged
    steps:
      - uses: actions/checkout@v2
      - name: Run E2E tests 🧪
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: 'http://localhost:3007'
          wait-on-timeout: 300
          command: yarn test:e2e:ci
          record: true
          browser: chrome
          group: 'Actions example'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots-e2e
          path: cypress/screenshots

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos-e2e
          path: cypress/videos

      - name: Render failure comment
        if: failure()
        id: template-failure
        uses: chuhlomin/render-template@v1.2
        with:
          template: .github/comment/pr-cypress-failure.md
          vars: |
            today: ${{ steps.vars.outputs.today }}
            job: ${{ github.job }}
            run_id: ${{ github.run_id }}
            run_number: ${{ github.run_number }}
            source: e2e

      - name: Publish failure comment
        if: failure()
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.template-failure.outputs.result }}
          edit-mode: replace

      - name: Render success comment
        id: template-success
        uses: chuhlomin/render-template@v1.2
        with:
          template: .github/comment/pr-cypress-success.md
          vars: |
            today: ${{ steps.vars.outputs.today }}
            job: ${{ github.job }}
            run_id: ${{ github.run_id }}
            run_number: ${{ github.run_number }}
            source: e2e

      - name: Publish success comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.template-success.outputs.result }}
          edit-mode: replace
