name: Test

on:
  pull_request:
    branches: [master]

jobs:
  test-e2e:
    name: E2E
    runs-on: ubuntu-latest
    outputs:
      check-ok: ${{ steps.output-ok.outputs.STATUS }}
      check-err: ${{ steps.output-err.outputs.STATUS }}
    container:
      image: cypress/browsers:node14.17.0-chrome88-ff89
      options: --privileged
    steps:
      - uses: actions/checkout@v2
#      - name: Run E2E tests 🧪
#        uses: cypress-io/github-action@v2
#        with:
#          start: yarn start:dev
#          wait-on: 'http://localhost:3007'
#          wait-on-timeout: 300
#          command: yarn test:e2e:ci
#          record: true
#          parallel: true
#          browser: chrome
#          cache-key: ${{ runner.os }}-hash-${{ hashFiles('yarn.lock') }}
#          group: 'Actions example'
#        env:
#          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: e2e-screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: e2e-videos
          path: cypress/videos

      - id: output-ok
        run: echo "::set-output name=STATUS::ok"
      - id: output-err
        if: failure()
        run: echo "::set-output name=STATUS::err"

  test-unit:
    name: Uint
    runs-on: ubuntu-latest
    outputs:
      check-ok: ${{ steps.output-ok.outputs.STATUS }}
      check-err: ${{ steps.output-err.outputs.STATUS }}
    container:
      image: cypress/browsers:node14.17.0-chrome88-ff89
      options: --privileged
    steps:
      - uses: actions/checkout@v2
#      - name: Run Unit tests 🧪
#        uses: cypress-io/github-action@v2
#        with:
#          command: yarn test:unit:ci
#          record: true
#          browser: chrome
#          group: 'Actions example'
#        env:
#          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Test error exit
        run: exit 1

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: unit-screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: unit-videos
          path: cypress/videos

      - id: output-ok
        run: echo "::set-output name=STATUS::ok"
      - id: output-err
        if: failure()
        run: echo "::set-output name=STATUS::err"

  completed-test:
    name: Completed test
    runs-on: ubuntu-latest
    needs: [test-e2e, test-unit]
    if: always()
    steps:
      - uses: actions/checkout@v2

      - name: Collect file
        run: |
          E2E_OK='${{ needs.test-e2e.outputs.check-ok }}'
          E2E_ERR='${{ needs.test-e2e.outputs.check-err }}'
          UNIT_OK='${{ needs.test-unit.outputs.check-ok }}'
          UNIT_ERR='${{ needs.test-unit.outputs.check-err }}'
          E2E_STATUS=${E2E_OK:-$E2E_ERR}
          UNIT_STATUS=${UNIT_OK:-$UNIT_ERR}

          mkdir -p test
          echo "${E2E_STATUS}" > test/e2e.log
          echo "${UNIT_STATUS}" > test/unit.log

      - uses: actions/upload-artifact@v1
        with:
          name: test
          path: test
